

all : build

build : 
	@cd src && $(MAKE)

clean:
	@cd src && $(MAKE) clean
	
help:
	@echo -e "make \t\t\tBuild"
	@echo -e "make build\t\tBuild the software"
	@echo -e "make clean\t\tRemove all files generated by make"
	@echo -e "make help\t\tDisplay this help"

#phony
.PHONY: all clean help
